### ISSUE TITLE
GitHub related request.

### ISSUE THREAD

**Issue by nepomnyi** [c-ding-math/functor-network#15]
Thank you very much for this wonderful project! Something like it has been long overdue!

1) The obvious question is whether or not your are committed to keep it free and open source forever. To answer this question, can you, please, add the LICENSE file to the source code?

2) I think it might be a good idea to enable the Discussions GitHub option for this project. If so, I found instructions on how to do it: https://docs.github.com/en/discussions/quickstart.

Thank you very much in advance.
Ivan

**Comment by c-ding-math** [comment]
Glad to hear you like this project.

1. I should add the BSD license in next commit.
2. The discussion has been enabled now.

**Comment by c-ding-math** [comment]
> Thank you very much for this wonderful project! Something like it has been long overdue!
> 
> 1. The obvious question is whether or not your are committed to keep it free and open source forever. To answer this question, can you, please, add the LICENSE file to the source code?
> 2. I think it might be a good idea to enable the Discussions GitHub option for this project. If so, I found instructions on how to do it: https://docs.github.com/en/discussions/quickstart.
> 
> Thank you very much in advance. Ivan

Glad to hear you like this project.

1. I should add the BSD license in next commit.
2. The discussion has been enabled now.
